const STAFF='release_probe_20261009',BRANCH='Main Office',ORIGIN='https://takodeal-staff.vercel.app';
const CONFIG={apiKey:'AIzaSyAmAWBbW7tTnIQkm2kTcJ-MLrjKHNGKcp4',authDomain:'takodeal-pos.firebaseapp.com',projectId:'takodeal-pos',storageBucket:'takodeal-pos.firebasestorage.app',messagingSenderId:'248826111383',appId:'1:248826111383:web:48bf1e2c172298079bd0d2'};
const el=id=>document.getElementById(id),onOrigin=location.origin===ORIGIN;
let modules,primary,unapproved,photo,photoUrl,record,operationId,orphanId,busy=false;
function log(label,data){el('log').textContent+='\n'+new Date().toISOString()+' '+label+(data===undefined?'':'\n'+JSON.stringify(data,null,2));el('log').scrollTop=el('log').scrollHeight;}
function origin(){if(location.origin!==ORIGIN)throw Error('Open the reviewed test route at the approved Staff address.');}
function code(error){return typeof error?.code==='string'?error.code:'local-validation';}
function same(client){origin();if(!client||client.auth.currentUser?.uid!==client.uid||client.auth.currentUser?.isAnonymous!==true)throw Error('The isolated synthetic account changed. Reload the test route.');}
function controls(){for(const button of document.querySelectorAll('[data-live]'))button.disabled=busy||!onOrigin||(button.hasAttribute('data-connected')&&!primary)||(button.id==='unapprovedDownload'&&!unapproved);}
async function run(label,task){if(busy)return;busy=true;controls();log('START '+label);try{const value=await task();log('RESULT '+label,value);}catch(error){log('ERROR '+label,{code:code(error),result:'No successful verification result. Stop and check the visible setup or connection.'});}finally{busy=false;controls();}}
async function sdk(){if(!modules)modules=Promise.all([import('https://www.gstatic.com/firebasejs/10.8.1/firebase-app.js'),import('https://www.gstatic.com/firebasejs/10.8.1/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/10.8.1/firebase-storage.js'),import('./modules/staff-document-firebase.js'),import('./modules/staff-document-store.js'),import('./modules/staff-document-broker.js')]).then(([app,auth,storage,firebase,store,broker])=>({app,auth,storage,firebase,store,broker}));return modules;}
async function client(label){origin();const m=await sdk(),app=m.app.initializeApp(CONFIG,'release-broker-'+label+'-'+crypto.randomUUID()),auth=m.auth.getAuth(app);await m.auth.setPersistence(auth,m.auth.inMemoryPersistence);const credential=await m.auth.signInAnonymously(auth);if(credential.user.isAnonymous!==true)throw Error('Only an isolated anonymous synthetic client is permitted.');const db=(await import('https://www.gstatic.com/firebasejs/10.8.1/firebase-firestore.js')).getFirestore(app);const result={m,app,auth,db,uid:credential.user.uid};same(result);result.store=m.store.createDocumentStore({sdk:m.firebase.documentSdk,db,auth,identity:()=>STAFF});result.broker=m.broker.createDocumentBroker({auth,identity:()=>STAFF});return result;}
async function jpeg(){if(photo)return photo;const canvas=document.createElement('canvas');canvas.width=1000;canvas.height=600;const c=canvas.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,1000,600);c.strokeStyle='#17634d';c.lineWidth=7;c.strokeRect(35,35,930,530);c.fillStyle='#183e32';c.textAlign='center';c.font='bold 44px sans-serif';c.fillText('SYSTEM VERIFICATION',500,235);c.font='bold 40px sans-serif';c.fillText('NO STAFF DATA',500,310);c.font='24px sans-serif';c.fillText('Token-free synthetic service probe · 2026-10-09',500,395);photo=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',0.88));if(!photo||photo.type!=='image/jpeg'||photo.size>2097152)throw Error('Synthetic JPEG generation failed.');return photo;}
function preview(blob){if(photoUrl)URL.revokeObjectURL(photoUrl);photoUrl=URL.createObjectURL(blob);el('preview').src=photoUrl;el('preview').hidden=false;}
function exact(value){if(!value||value.staffId!==STAFF||value.branch!==BRANCH||value.group!=='valid_id'||!/^broker-probe-[A-Za-z0-9_-]+$/.test(value.uploadId)||value.storagePath!==`staff_private_documents/${value.uploadedByUid}/${STAFF}/valid_id/${value.uploadId}.jpg`)throw Error('The current verified synthetic upload is required.');return value;}
function saved(){same(primary);return exact(record);}
async function policy(clientValue=primary){same(clientValue);const value=await clientValue.store.ready({refresh:true});same(clientValue);return value;}
async function approved(){same(primary);const value=await primary.store.binding();same(primary);if(value.staffId!==STAFF||value.branch!==BRANCH)throw Error('Only the Main Office synthetic approval is permitted.');return value;}
async function assertDenial(label,task,allowed=['storage/unauthorized','permission-denied','firestore/permission-denied','document-broker/permission-denied']){try{await task();return {test:label,verdict:'FAIL: unexpectedly allowed; stop before real uploads'};}catch(error){return {test:label,verdict:allowed.includes(code(error))?'PASS: refused':'INCONCLUSIVE: unexpected error',code:code(error)};}}
function downloadBody(value){return {staffId:STAFF,group:'valid_id',uploadId:value.uploadId,version:value.version,sha256:value.sha256};}
el('originState').textContent=onOrigin?'Approved Staff address. No operations have run.':'Local preview only. Production controls are disabled at this address.';controls();
el('connect').onclick=()=>run('create isolated synthetic client',async()=>{if(!primary)primary=await client('pilot');same(primary);el('pilotUid').textContent=primary.uid;el('seed').textContent=JSON.stringify({requestPath:'staff_document_requests/'+primary.uid,bindingPath:'staff_document_devices/'+primary.uid,immutableIdentity:{uid:primary.uid,staffId:STAFF,branch:BRANCH},scopePath:'staff_private_documents/'+STAFF,note:'Approve only this synthetic pilot through the reviewed Owner approval flow or Console. Required approvedAt/approvedByUid/audit fields must remain intact. No cashiers profile is created.'},null,2);return {uid:primary.uid,staffId:STAFF,isAnonymous:true,persistence:'memory only',businessWrites:0};});
el('policy').onclick=()=>run('read exact v2 policy',async()=>{const value=await policy();return {enabled:value.enabled,policyVersion:value.policyVersion,brokerEndpoint:value.brokerEndpoint};});
el('request').onclick=()=>run('submit fixed synthetic device approval request',async()=>{same(primary);return primary.store.requestDevice({deviceId:'broker-release-probe-20261009',deviceName:'SYSTEM VERIFICATION - NO STAFF DATA'});});
el('binding').onclick=()=>run('check fixed synthetic approval',async()=>{const value=await approved();return {uid:primary.uid,staffId:STAFF,branch:BRANCH,active:value.active};});
el('photo').onclick=()=>run('generate local synthetic JPEG',async()=>{const blob=await jpeg();preview(blob);return {type:blob.type,size:blob.size,cloudOperations:0};});
el('records').onclick=()=>run('read synthetic document records',async()=>{same(primary);const values=await primary.store.records();same(primary);return Object.fromEntries(Object.entries(values).map(([kind,value])=>[kind,value?{group:kind,version:value.version,status:value.status,uploadId:value.uploadId}:null]));});
function showRecord(){el('record').textContent=JSON.stringify(record,null,2);el('inspection').textContent=JSON.stringify({bucket:CONFIG.storageBucket,exactObject:record.storagePath,sha256:record.sha256,size:record.size,expectedAbsentMetadataKey:'firebaseStorageDownloadTokens',expectedObjectPolicy:'No public ACL/IAM grant; private,no-store',note:'Read token presence only in Console. Never generate or copy a shareable link.'},null,2);}
el('upload').onclick=()=>run('actual store upload plus atomic metadata commit',async()=>{await approved();const before=await primary.store.records();same(primary);const blob=await jpeg();same(primary);operationId||='broker-probe-'+crypto.randomUUID();const result=await primary.store.upload('valid_id',blob,{group:'valid_id'},before.valid_id?.version||0,operationId);same(primary);record=exact(result.record);preview(blob);showRecord();return {saved:result.saved===true,alreadySaved:result.alreadySaved===true,uploadId:record.uploadId,version:record.version,sha256:record.sha256,size:record.size};});
el('download').onclick=()=>run('actual store authenticated download and SHA verification',async()=>{const value=saved(),blob=await primary.store.file(value);same(primary);preview(blob);return {verdict:'PASS: actual store verified saved JPEG',type:blob.type,size:blob.size,uploadId:value.uploadId,sha256:value.sha256};});
el('stale').onclick=()=>run('replace synthetic file and refuse old service reference',async()=>{const old=saved();await approved();const blob=await jpeg();same(primary);const id='broker-probe-'+crypto.randomUUID(),result=await primary.store.upload('valid_id',blob,{group:'valid_id'},old.version,id);same(primary);record=exact(result.record);operationId=id;showRecord();const config=await policy();return assertDenial('prior synthetic reference after replacement',()=>primary.broker.download(config,downloadBody(old)),['document-broker/failed-precondition']);});
el('direct').onclick=()=>run('direct private Storage SDK denials',async()=>{const value=saved(),m=primary.m.storage,storage=m.getStorage(primary.app),ref=m.ref(storage,value.storagePath),results=[];for(const [label,task] of [['JPEG bytes',()=>m.getBytes(ref,2097152)],['metadata',()=>m.getMetadata(ref)],['shareable link creation',()=>m.getDownloadURL(ref)],['private-prefix list',()=>m.listAll(m.ref(storage,`staff_private_documents/${primary.uid}/${STAFF}`))],['overwrite current synthetic JPEG',async()=>m.uploadBytes(ref,await jpeg(),{contentType:'image/jpeg'})]]){same(primary);results.push(await assertDenial(label,task));same(primary);if(!results.at(-1).verdict.startsWith('PASS:'))break;}return results;});
el('noAuth').onclick=()=>run('service download with no authentication header',async()=>{const value=saved();let response;try{response=await fetch(primary.m.broker.DOCUMENT_BROKER_ENDPOINT+'/download',{method:'POST',mode:'cors',headers:{'Content-Type':'application/json'},credentials:'omit',cache:'no-store',redirect:'error',referrerPolicy:'no-referrer',signal:AbortSignal.timeout(30000),body:JSON.stringify(downloadBody(value))});}catch{return {verdict:'INCONCLUSIVE: service CORS/network/redirect prevented a response'};}const bytes=new Uint8Array(await response.arrayBuffer());same(primary);const jpeg=bytes[0]===255&&bytes[1]===216;return {httpStatus:response.status,jpegMagic:jpeg,verdict:response.status===401&&!jpeg?'PASS: unauthenticated service request refused':response.ok||jpeg?'FAIL: unauthenticated service returned bytes':'INCONCLUSIVE: expected service authentication refusal was not proven'};});
async function anonymousObject(url,label){try{const response=await fetch(url,{credentials:'omit',cache:'no-store',redirect:'error',referrerPolicy:'no-referrer',signal:AbortSignal.timeout(30000)}),bytes=new Uint8Array(await response.arrayBuffer());same(primary);const jpeg=bytes[0]===255&&bytes[1]===216;return {test:label,httpStatus:response.status,byteLength:bytes.length,jpegMagic:jpeg,verdict:[401,403].includes(response.status)&&!jpeg?'PASS: anonymous exact-object access refused':response.ok||jpeg?'FAIL: anonymous object was readable':'INCONCLUSIVE: object refusal was not proven'};}catch{return {test:label,verdict:'INCONCLUSIVE: CORS/network/redirect prevented reading the response'};}}
el('anonymous').onclick=()=>run('anonymous exact synthetic object checks without tokens',async()=>{const value=saved();await primary.store.file(value);same(primary);const bucket=encodeURIComponent(CONFIG.storageBucket);const results=[];results.push(await anonymousObject('https://firebasestorage.googleapis.com/v0/b/'+bucket+'/o/'+encodeURIComponent(value.storagePath)+'?alt=media','Firebase anonymous bytes, no token'));same(primary);results.push(await anonymousObject('https://storage.googleapis.com/'+bucket+'/'+value.storagePath.split('/').map(encodeURIComponent).join('/'),'GCS anonymous bytes'));return results;});
el('unapprovedConnect').onclick=()=>run('create never-approved synthetic client',async()=>{if(!unapproved)unapproved=await client('unapproved');same(unapproved);if(unapproved.uid===primary?.uid)throw Error('The unapproved client must be distinct.');el('unapprovedUid').textContent=unapproved.uid+' — never approve this UID';return {uid:unapproved.uid,isAnonymous:true,persistence:'memory only',businessWrites:0};});
el('unapprovedDownload').onclick=()=>run('unapproved direct service download denial',async()=>{const value=saved(),config=await policy(unapproved);same(unapproved);return assertDenial('unapproved service bytes',()=>unapproved.broker.download(config,downloadBody(value)));});
el('revokedDownload').onclick=()=>run('revoked pilot direct service download denial',async()=>{const value=saved(),config=await policy();return assertDenial('revoked pilot service bytes',()=>primary.broker.download(config,downloadBody(value)));});
el('orphan').onclick=()=>run('synthetic bytes without metadata must not download',async()=>{const value=saved();await approved();const config=await policy(),blob=await jpeg(),bytes=new Uint8Array(await blob.arrayBuffer());same(primary);const sha256=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),byte=>byte.toString(16).padStart(2,'0')).join('');same(primary);orphanId||='broker-orphan-'+crypto.randomUUID();const transferred=await primary.broker.upload(config,{staffId:STAFF,group:'valid_id',uploadId:orphanId,expectedVersion:value.version,sha256,clearanceType:'',expiresOn:'',bytes});same(primary);el('orphanRecord').textContent=JSON.stringify({exactObject:transferred.storagePath,uploadId:orphanId,metadataCommitted:false,cleanup:'Remove only this synthetic orphan through Console after checking it.'},null,2);return assertDenial('uncommitted synthetic service bytes',()=>primary.broker.download(config,{staffId:STAFF,group:'valid_id',uploadId:orphanId,version:value.version+1,sha256}),['document-broker/failed-precondition']);});
el('save').onclick=()=>{const blob=new Blob([el('log').textContent],{type:'text/plain'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='synthetic-token-free-document-verification.log';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
window.addEventListener('pagehide',()=>{if(photoUrl)URL.revokeObjectURL(photoUrl);});
