import test from 'node:test';
import assert from 'node:assert/strict';
import {prepareGuidedDraft, dateLabel, createDraftStore, publishReviewedDraft, publicationMatches, validateDraft, visibleAnnouncement, uniqueSignatures, escapeHTML} from '../takodeal-manager/ai-hub-model.js';

const owner = {isOwner:true,cashierName:'Sample Manager'};
const draft = overrides => ({id:'hub-12345678-abcd',title:'Opening checklist',subHeadline:'Effective tomorrow',message:'Verify the opening checklist with the shift leader.',footerMessage:'Management',targetType:'All',...overrides});
function harness() {
    const rows = new Map(); let uploads = 0, commits = 0, loseResponse = false;
    const adapter = {
        async read(id) { return rows.get(id); },
        async upload(id,index) { uploads++; return `https://example.test/${id}/${index}`; },
        async commit(id,payload) {
            if (rows.has(id)) { assert.ok(publicationMatches(rows.get(id),payload)); return {id,existing:true}; }
            commits++; rows.set(id,payload);
            if (loseResponse) { loseResponse = false; throw new Error('Response lost after commit'); }
            return {id,existing:false};
        }
    };
    return {rows,adapter,uploads:()=>uploads,commits:()=>commits,loseResponse:()=>{loseResponse=true;}};
}
const options = h => ({user:owner,uid:'manager-1',online:true,reviewed:true,adapter:h.adapter});

test('guided drafts preserve supplied facts and dates, use formal wording, and identify their template source',() => {
    const facts = 'Inspect the refrigerator at 8:00 AM.\nRecord the temperature.';
    const result = prepareGuidedDraft({type:'policy',title:'Food storage',facts,date:'2026-10-15'},{id:'hub-test12345',now:100});
    assert.ok(result.message.includes(facts)); assert.equal(result.title,'Food storage');
    assert.equal(result.subHeadline,'Effective October 15, 2026'); assert.equal(result.source,'guided-template');
    assert.equal(result.createdAt,100); assert.equal(result.id,'hub-test12345');
    assert.doesNotMatch(result.message,/cartoon|Gemini|generated by AI/i);
    assert.throws(()=>prepareGuidedDraft({title:'Notice',facts:''}),/facts/);
    assert.throws(()=>prepareGuidedDraft({title:'Notice',facts:'A fact',date:'2026-02-30'}),/valid effective/);
    assert.equal(dateLabel('2026-02-30'),'');
});
test('private drafts survive a new store instance and are separated by signed-in account',() => {
    const values = new Map(), storage = {getItem:key=>values.get(key),setItem:(key,value)=>values.set(key,value)};
    const first = createDraftStore(storage,'manager-1'); first.save(draft({updatedAt:123}));
    assert.equal(createDraftStore(storage,'manager-1').list()[0].updatedAt,123);
    assert.deepEqual(createDraftStore(storage,'manager-2').list(),[]);
    first.save(draft({title:'Edited title'})); assert.equal(first.list().length,1);
    first.remove(draft().id); assert.deepEqual(first.list(),[]);
});
test('unavailable draft storage and missing identity never report a successful save',() => {
    const unavailable = createDraftStore({getItem(){throw Error('blocked');},setItem(){throw Error('full');}},'manager-1');
    assert.equal(unavailable.save(draft()),false); assert.match(unavailable.error(),/not saved/);
    assert.equal(createDraftStore({},'').save(draft()),false);
});
test('a full draft library does not silently delete older drafts',() => {
    const values = new Map(), storage = {getItem:key=>values.get(key),setItem:(key,value)=>values.set(key,value)};
    const store = createDraftStore(storage,'manager-1');
    for(let i=0;i<20;i++) assert.equal(store.save(draft({id:'hub-draft-'+i})),true);
    assert.equal(store.save(draft({id:'hub-draft-21'})),false); assert.match(store.error(),/20 drafts/);
    assert.equal(store.list().length,20); assert.ok(store.list().some(row=>row.id==='hub-draft-0'));
});
test('a reviewed text-only announcement publishes with no image requirement',async () => {
    const h = harness(); const result = await publishReviewedDraft(draft(),[],options(h));
    assert.equal(result.existing,false); assert.deepEqual(h.rows.get(result.id).images,[]);
    assert.equal(h.rows.get(result.id).publisherUid,'manager-1'); assert.equal(h.commits(),1);
});
test('an individual notice retains private routing and does not target a branch',async () => {
    const h = harness(); await publishReviewedDraft(draft({targetType:'Individual',targetStaff:'Sample Staff',targetBranch:'Maa'}),[],options(h));
    const row = h.rows.get(draft().id); assert.equal(row.isPrivateMessage,true); assert.equal(row.targetStaff,'Sample Staff'); assert.equal(row.targetBranch,null);
});
test('a selected branch is required and only branch notices persist that target',async () => {
    const h = harness(); await assert.rejects(publishReviewedDraft(draft({targetType:'Branch'}),[],options(h)),/target branch/);
    assert.equal(h.rows.size,0);
    await publishReviewedDraft(draft({targetType:'Branch',targetBranch:'Cabantian',targetStaff:'Ignored'}),[],options(h));
    assert.equal(h.rows.get(draft().id).targetStaff,null); assert.equal(h.rows.get(draft().id).targetBranch,'Cabantian');
});
test('permissions, review, network, and identity are checked before any external write',async () => {
    const h = harness();
    for (const override of [{reviewed:false},{online:false},{uid:''},{user:{isOwner:true,isFranchisee:true}},{user:{permissions:[]}}]) {
        await assert.rejects(publishReviewedDraft(draft(),[],{...options(h),...override}));
    }
    assert.equal(h.commits(),0); assert.equal(h.uploads(),0);
});
test('retry after a lost publication response creates no second announcement and preserves archived state',async () => {
    const h = harness(); h.loseResponse();
    await assert.rejects(publishReviewedDraft(draft(),[],options(h)),/Response lost/);
    h.rows.get(draft().id).active = false;
    const retry = await publishReviewedDraft(draft(),[],options(h));
    assert.equal(retry.existing,true); assert.equal(h.commits(),1); assert.equal(h.rows.get(draft().id).active,false);
});
test('changing an already-published draft cannot replace its content',async () => {
    const h = harness(); await publishReviewedDraft(draft(),[],options(h));
    await assert.rejects(publishReviewedDraft(draft({message:'A different message'}),[],options(h)),/already been published/);
    assert.equal(h.rows.get(draft().id).message,draft().message); assert.equal(h.commits(),1);
});
test('attachment failure retains an unpublished draft and prevents a partial notice',async () => {
    const h = harness(); h.adapter.upload = async () => {throw new Error('Upload unavailable');};
    await assert.rejects(publishReviewedDraft(draft(),[{type:'image/png',size:100}],options(h)),/Upload unavailable/);
    assert.equal(h.commits(),0); assert.equal(h.rows.size,0);
});
test('unsafe or oversized uploads are rejected before uploading',() => {
    assert.match(validateDraft(draft(),[{type:'image/svg+xml',size:10}]).join(' '),/JPG/);
    assert.match(validateDraft(draft(),[{type:'image/jpeg',size:6*1024*1024}]).join(' '),/5 MB/);
    assert.match(validateDraft(draft(),Array(9).fill({type:'image/png',size:1})).join(' '),/8 images/);
});
test('franchise history excludes other branches and private notices intended for another person',() => {
    const user = {isFranchisee:true,allowedBranches:['Maa'],cashierName:'Sample Owner'};
    assert.equal(visibleAnnouncement({targetType:'Branch',targetBranch:'Maa'},user),true);
    assert.equal(visibleAnnouncement({targetType:'Branch',targetBranch:'Cabantian'},user),false);
    assert.equal(visibleAnnouncement({targetType:'Individual',targetStaff:'Other Person'},user),false);
    assert.equal(visibleAnnouncement({targetType:'Individual',targetStaff:'Sample Owner'},user),true);
    assert.equal(visibleAnnouncement({targetType:'All'},null),false);
});
test('signature counts represent unique named signers, not duplicate records',() => {
    assert.equal(uniqueSignatures([{staffName:'Ana'},{staffName:' ana '},{staffName:''},{staffName:'Ben'}]).length,2);
});
test('announcement previews and history escape markup and attribute-breaking text',() => {
    assert.equal(escapeHTML('<img src=x onerror="x">\'&'), '&lt;img src=x onerror=&quot;x&quot;&gt;&#39;&amp;');
});
