import test from 'node:test';
import assert from 'node:assert/strict';
import {renderRiderDispatch,riderMapURL,riderMoney} from '../takodeal-delivery/rider-dispatch-view.js';
function fixture(){const nodes=new Map();const node=id=>{if(!nodes.has(id))nodes.set(id,{style:{},textContent:'',innerHTML:'',setAttribute(key,value){this[key]=value;},replaceChildren(){this.innerHTML='';}});return nodes.get(id);};const api={currentRider:{id:'rider-a',status:'active',isAcceptingOrders:true},activeDeliveries:[],currentRiderTab:'Pending',isRiderApproved:rider=>rider?.status==='active'};return {api,node,render:()=>renderRiderDispatch(api,{getElementById:node})};}
const ready={id:'delivery-1',orderCode:'TK-1',status:'ready',orderType:'Delivery',branch:'Sample branch',customerName:'Sample customer',contactNumber:'09000000000',deliveryAddress:'Sample address',totalAmount:150,deliveryFee:0,paymentMode:'Cash'};
test('ready delivery board becomes visible with exact cash wallet cost and a zero delivery fee',()=>{const h=fixture();h.api.activeDeliveries=[ready];h.render();assert.equal(h.node('dispatchBoard').style.display,'flex');assert.equal(h.node('dispatchBoardContainer').style.display,'block');assert.equal(h.node('radarScreen').style.display,'none');assert.match(h.node('dispatchBoard').innerHTML,/Wallet ₱150.00/);assert.match(h.node('dispatchBoard').innerHTML,/₱0.00/);assert.equal(h.node('riderOpenCount').textContent,'1');});
test('My deliveries shows only the exact assigned rider and empty tabs cannot leave an invisible board',()=>{const h=fixture();h.api.currentRiderTab='Ongoing';h.api.activeDeliveries=[ready,{...ready,id:'mine',status:'out_for_delivery',riderId:'rider-a'},{...ready,id:'other',status:'out_for_delivery',riderId:'rider-b'}];h.render();assert.match(h.node('dispatchBoard').innerHTML,/mine/);assert.doesNotMatch(h.node('dispatchBoard').innerHTML,/other|TK-1.*Accept delivery/);assert.equal(h.node('riderOngoingCount').textContent,'1');h.api.activeDeliveries=[ready];h.render();assert.equal(h.node('radarScreen').style.display,'flex');assert.equal(h.node('riderEmptyTitle').textContent,'No deliveries in progress');assert.equal(h.node('dispatchBoard').innerHTML,'');});
test('suspended and pending accounts clear their delivery content and cannot receive action buttons',()=>{const h=fixture();h.api.activeDeliveries=[ready];h.render();for(const status of ['pending_approval','rejected','banned','unknown']){h.api.currentRider.status=status;h.render();assert.equal(h.node('dispatchBoard').innerHTML,'');assert.equal(h.node('riderOpenCount').textContent,'0');assert.equal(h.node('riderEmptyTitle').textContent,'Approval required');}});
test('offline availability disables new cash claims while retaining an assigned delivery completion',()=>{const h=fixture();h.api.currentRider.isAcceptingOrders=false;h.api.activeDeliveries=[ready];h.render();assert.match(h.node('dispatchBoard').innerHTML,/disabled/);h.api.currentRiderTab='Ongoing';h.api.activeDeliveries=[{...ready,status:'out_for_delivery',riderId:'rider-a'}];h.render();assert.match(h.node('dispatchBoard').innerHTML,/Mark delivered/);assert.doesNotMatch(h.node('dispatchBoard').innerHTML,/disabled/);});
test('untrusted customer/branch/order data is escaped and cannot create HTML or inline-handler injection',()=>{const h=fixture();h.api.activeDeliveries=[{...ready,id:"job' onclick='evil",orderCode:'<img src=x onerror=evil()>',customerName:'<svg onload=evil()>',branch:'<script>evil()</script>',deliveryAddress:'<iframe src=evil>',contactNumber:'javascript:evil()',mapLink:'javascript:evil()'}];h.render();const html=h.node('dispatchBoard').innerHTML;assert.doesNotMatch(html,/<img src=x|<svg |<script>|<iframe |href="javascript:|onclick='evil/);assert.match(html,/&lt;img src=x/);assert.match(html,/No customer phone/);assert.match(html,/google.com\/maps\/search/);assert.match(html,/%27/);assert.match(html,/rel="noopener noreferrer"/);});
test('safe map origins preserve pinned links and unsafe schemes/hosts fall back to an encoded address',()=>{assert.equal(riderMapURL({...ready,mapLink:'https://maps.app.goo.gl/sample'}),'https://maps.app.goo.gl/sample');for(const mapLink of ['data:text/html,evil','javascript:evil()','https://attacker.invalid/foo','http://google.com/maps']){const url=riderMapURL({...ready,mapLink,deliveryAddress:'A & B #1'});assert.equal(url,'https://www.google.com/maps/search/?api=1&query=A%20%26%20B%20%231');}});
test('prepaid order card does not advertise a wallet debit and malformed totals are visibly unconfirmed',()=>{const h=fixture();h.api.activeDeliveries=[{...ready,paymentMode:'Online'}];h.render();assert.match(h.node('dispatchBoard').innerHTML,/Manager must verify/);assert.doesNotMatch(h.node('dispatchBoard').innerHTML,/Wallet ₱/);assert.equal(riderMoney('150.50'),'₱150.50');for(const bad of [undefined,true,-1,'',NaN,Infinity])assert.equal(riderMoney(bad),'Amount unavailable');});
