const STAFF='release_probe_20261009',BRANCH='Main Office',ORIGIN='https://takodeal-owner.vercel.app',OWNER='jgo031996@gmail.com';
const CONFIG={apiKey:'AIzaSyAmAWBbW7tTnIQkm2kTcJ-MLrjKHNGKcp4',authDomain:'takodeal-pos.firebaseapp.com',projectId:'takodeal-pos',storageBucket:'takodeal-pos.firebasestorage.app',messagingSenderId:'248826111383',appId:'1:248826111383:web:48bf1e2c172298079bd0d2'};
const el=id=>document.getElementById(id),onOrigin=location.origin===ORIGIN;let modules,client,record,photoUrl,busy=false;
function log(label,data){el('log').textContent+='\n'+new Date().toISOString()+' '+label+(data===undefined?'':'\n'+JSON.stringify(data,null,2));el('log').scrollTop=el('log').scrollHeight;}
function origin(){if(location.origin!==ORIGIN)throw Error('Use the approved Owner address.');}
function same(captured=client){origin();const user=client?.auth.currentUser;if(!client||client!==captured||user!==client.user||user.uid!==client.uid||user.isAnonymous||user.emailVerified!==true||String(user.email||'').toLowerCase()!==OWNER||!user.providerData?.some(provider=>provider.providerId==='google.com'))throw Error('The verified Owner account changed. Sign in again.');return client;}
function controls(){for(const button of document.querySelectorAll('[data-live]'))button.disabled=busy||!onOrigin||(button.hasAttribute('data-connected')&&!client);}
async function run(label,task){if(busy)return;busy=true;controls();log('START '+label);try{log('RESULT '+label,await task());}catch(error){log('ERROR '+label,{code:typeof error?.code==='string'?error.code:'local-validation',result:'No successful verification result. Check the approved account, synthetic setup and connection.'});}finally{busy=false;controls();}}
async function sdk(){if(!modules)modules=Promise.all([import('https://www.gstatic.com/firebasejs/10.8.1/firebase-app.js'),import('https://www.gstatic.com/firebasejs/10.8.1/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/10.8.1/firebase-firestore.js'),import('https://www.gstatic.com/firebasejs/10.8.1/firebase-storage.js'),import('./modules/staff-document-firebase.js'),import('./modules/staff-document-store.js')]).then(([app,auth,firestore,storage,firebase,store])=>({app,auth,firestore,storage,firebase,store}));return modules;}
function exact(value){if(!value||value.staffId!==STAFF||value.branch!==BRANCH||value.group!=='valid_id'||!/^broker-probe-[A-Za-z0-9_-]+$/.test(value.uploadId)||value.storagePath!==`staff_private_documents/${value.uploadedByUid}/${STAFF}/valid_id/${value.uploadId}.jpg`)throw Error('Upload the new token-free synthetic photo through the Staff page first.');return value;}
async function denied(label,task){try{await task();return {test:label,verdict:'FAIL: unexpectedly allowed; stop before real uploads'};}catch(error){const code=typeof error?.code==='string'?error.code:'unknown';return {test:label,code,verdict:code==='storage/unauthorized'?'PASS: refused':'INCONCLUSIVE: unexpected error'};}}
el('originState').textContent=onOrigin?'Approved Owner address. No operations have run.':'Local preview only. Production controls are disabled at this address.';controls();
el('signIn').onclick=()=>run('isolated verified Owner Google sign-in',async()=>{origin();if(client){same();return {alreadySignedIn:true,uid:client.uid};}const m=await sdk(),app=m.app.initializeApp(CONFIG,'release-owner-broker-'+crypto.randomUUID()),auth=m.auth.getAuth(app);await m.auth.setPersistence(auth,m.auth.inMemoryPersistence);const provider=new m.auth.GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});const result=await m.auth.signInWithPopup(auth,provider),user=result.user;if(user.isAnonymous||user.emailVerified!==true||String(user.email||'').toLowerCase()!==OWNER||!user.providerData?.some(value=>value.providerId==='google.com')){await m.auth.signOut(auth);throw Error('Only the verified Owner Google account is permitted.');}client={m,app,auth,user,uid:user.uid,db:m.firestore.getFirestore(app)};same();client.store=m.store.createDocumentStore({sdk:m.firebase.documentSdk,db:client.db,auth,identity:()=>STAFF,isHQ:true});const captured=client;m.auth.onAuthStateChanged(auth,value=>{if(client!==captured)return;if(value?.uid!==captured.uid){record=null;if(photoUrl)URL.revokeObjectURL(photoUrl);photoUrl=null;el('preview').hidden=true;el('preview').removeAttribute('src');el('record').textContent='Owner account changed; previous synthetic result cleared.';el('ownerState').textContent='Account changed. Reload this test page to sign in again.';client=null;controls();}});el('ownerState').textContent='Verified Owner signed in — '+client.uid;return {uid:client.uid,emailVerified:true,provider:'google.com',persistence:'memory only',businessWrites:0};});
el('policy').onclick=()=>run('Owner read exact v2 service policy',async()=>{const c=same(),config=await c.store.ready({refresh:true});same(c);return {enabled:config.enabled,policyVersion:config.policyVersion,brokerEndpoint:config.brokerEndpoint};});
el('download').onclick=()=>run('verified Owner store download of fixed synthetic JPEG',async()=>{const c=same(),values=await c.store.records();same(c);const selected=exact(values.valid_id),blob=await c.store.file(selected,{validatePhoto:async photo=>{const bitmap=await createImageBitmap(photo);const valid=bitmap.width>0&&bitmap.height>0;bitmap.close?.();if(!valid)throw Error('Synthetic JPEG did not decode.');same(c);}});same(c);record=selected;if(photoUrl)URL.revokeObjectURL(photoUrl);photoUrl=URL.createObjectURL(blob);el('preview').src=photoUrl;el('preview').hidden=false;el('record').textContent=JSON.stringify({staffId:STAFF,branch:BRANCH,uploadId:record.uploadId,version:record.version,storagePath:record.storagePath,sha256:record.sha256,size:blob.size},null,2);return {verdict:'PASS: reviewed HQ store verified and decoded synthetic JPEG',type:blob.type,size:blob.size,uploadId:record.uploadId,sha256:record.sha256,businessWrites:0};});
el('direct').onclick=()=>run('verified Owner direct private Storage denials',async()=>{const c=same(),value=exact(record),m=c.m.storage,ref=m.ref(m.getStorage(c.app),value.storagePath),results=[];for(const [label,task]of [['JPEG bytes',()=>m.getBytes(ref,2097152)],['metadata',()=>m.getMetadata(ref)],['shareable link creation',()=>m.getDownloadURL(ref)]]){same(c);results.push(await denied(label,task));same(c);if(!results.at(-1).verdict.startsWith('PASS:'))break;}return results;});
el('save').onclick=()=>{const url=URL.createObjectURL(new Blob([el('log').textContent],{type:'text/plain'})),a=document.createElement('a');a.href=url;a.download='synthetic-owner-token-free-document-verification.log';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
window.addEventListener('pagehide',()=>{if(photoUrl)URL.revokeObjectURL(photoUrl);});
